### ISSUE TITLE
Label for checkbox is misaligned. It is slightly downward to checkbox

### ISSUE THREAD

**Issue by goforgold** [TalksLab/metro-bootstrap#27]
![checkbox](https://f.cloud.github.com/assets/1727061/704905/8fc84300-ddca-11e2-8227-e59dbeb59667.png)

As you can see in the image, label for checkbox is slightly moving to downward. This behavior is not found in original bootstrap.

**Comment by NelsonReis** [comment]
Unfortunately, we no longer have the time to work on this project. This means that bugs will not be fixed and features will not be added unless someone else does so.

If you're interested in fixing up metro-bootstrap, please reply to this [GitHub issue (#65)](https://github.com/TalksLab/metro-bootstrap/issues/65).

Thank you for your support.

**Comment by Bashamega** [comment]
Hello @goforgold 

Sorry for the late reply, this project was inactive, but i am trying to fix it.
Are you using the latest version, and you don't have any overriding CSS?
On the main site it seems to work:
![image](https://github.com/user-attachments/assets/8d982816-939a-4769-825c-46f2b52833f9)
You can try it for this link: https://talkslab.github.io/metro-bootstrap/components.html#input-groups

**Comment by goforgold** [comment]
> Hello @goforgold
> 
> Sorry for the late reply, this project was inactive, but i am trying to fix it. Are you using the latest version, and you don't have any overriding CSS? On the main site it seems to work: ![image](https://private-user-images.githubusercontent.com/110662505/379680750-8d982816-939a-4769-825c-46f2b52833f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4Mzc5MjMsIm5iZiI6MTcyOTgzNzYyMywicGF0aCI6Ii8xMTA2NjI1MDUvMzc5NjgwNzUwLThkOTgyODE2LTkzOWEtNDc2OS04MjVjLTQ2ZjJiNTI4MzNmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQwNjI3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OWEzZWRhNGZjM2I0MzdiNWM4ZDllZTQ5ZjY2ZTc4MDAwYTQwMTIyM2I1NGY4NmYxZDM2NjRmZGIyMzc0NDM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Pp2v_KJPqMmMKuCNWZaoTYKKfgBmIlm1kv5VP7KCQr4) You can try it for this link: https://talkslab.github.io/metro-bootstrap/components.html#input-groups

The project where I was using this library has long back migrated to ReactJs with MUI custom theme. I think we can close this issue.

**Comment by Bashamega** [comment]
I am very sorry for the inconvenience.
