### ISSUE TITLE
Using metro-bootstrap with Font-Awesome-icons in tiles

### ISSUE THREAD

**Issue by z0nk** [TalksLab/metro-bootstrap#30]
Hi,
I am trying to use the Font-Awesome-icons in the tiles.
this is my code:

``` html
<ul class="thumbnails">
      <li class="span3 tile tile-double">
          <a href="#">
              <i class="icon-tasks icon-large icon-5x"></i>
             <h1 class="tile-text">Task</h1>
          </a>
      </li>
</ul>
```

the issue is that there is no text visible and the icon is only visible if there is a mouse-hover event. what am i doing wrong?

**Comment by NelsonReis** [comment]
Unfortunately, we no longer have the time to work on this project. This means that bugs will not be fixed and features will not be added unless someone else does so.

If you're interested in fixing up metro-bootstrap, please reply to this [GitHub issue (#65)](https://github.com/TalksLab/metro-bootstrap/issues/65).

Thank you for your support.

**Comment by Bashamega** [comment]
Hello @z0nk 
Sorry for the late reply, this project was inactive.
It seems that the issue is solved.
On the main website and example is working
Code:
```
<div class="col-sm-6 col-md-3">
	<div class="thumbnail tile tile-medium">
		<a href="#" >
			<img src="images/twittertile.png">
			<h2>
			Tweet
			</h2>
		</a>
	</div>
</div>
```
![image](https://github.com/user-attachments/assets/df0baaaf-808b-4333-b8ff-b4a9393971c9)
