### ISSUE TITLE
some ideas for enhancements

### ISSUE THREAD

**Issue by z0nk** [TalksLab/metro-bootstrap#32]
Just in case this project is still active. maybe you coul add the following to your project:
- more colors to choose from:
  http://www.creepyed.com/2012/09/windows-8-colors-hex-code/
- add optional the text in tiles in small light font in left corner (like in win8) for tile description
- add optional the text in tiles in small bold font in right corner (like in win8) for some counter or short info
- command buttons. they are usually in the top left corner in win8 (arrows for back navigation i.e.)

**Comment by NelsonReis** [comment]
Unfortunately, we no longer have the time to work on this project. This means that bugs will not be fixed and features will not be added unless someone else does so.

If you're interested in fixing up metro-bootstrap, please reply to this [GitHub issue (#65)](https://github.com/TalksLab/metro-bootstrap/issues/65).

Thank you for your support.

**Comment by Bashamega** [comment]
Hello @z0nk 

We are very sorry, for the late reply, the project was inactive. 

Thanks

**Comment by Bashamega** [comment]
Nice Idea.

**Comment by Bashamega** [comment]
> Metro tiles could benefit from a more responsive behaviour. It is not easy to use several of them in a small screen.

Fore this you need to modify your grid layout.
