### ISSUE TITLE
Colors Dislocation <IE>

### ISSUE THREAD

**Issue by hyyyp** [TalksLab/metro-bootstrap#52]
.col-sm-6
position:relative
min-height:1px   /\*  !!!   Change 0px */
padding-left:15px
padding-right:15px

/css/metro-bootstrap.css

**Comment by NelsonReis** [comment]
Unfortunately, we no longer have the time to work on this project. This means that bugs will not be fixed and features will not be added unless someone else does so.

If you're interested in fixing up metro-bootstrap, please reply to this [GitHub issue (#65)](https://github.com/TalksLab/metro-bootstrap/issues/65).

Thank you for your support.

**Comment by Bashamega** [comment]
This issue needs more info
