### ISSUE TITLE
Why the NuGet package have a dependency on FontAwesome?

### ISSUE THREAD

**Issue by Jak3b0** [TalksLab/metro-bootstrap#56]
Hi,

I just installed the NuGet package for Metro Bootstrap and I do not quite understand why it have a dependency on the Font Awesome package. In my project, I am using the Less version of FontAwesome and this requires me to have both. Looking at the sources of Metro Bootstrap, I do not quite understand why this dependency is required.

Thank you,

Jacques.

**Comment by NelsonReis** [comment]
Unfortunately, we no longer have the time to work on this project. This means that bugs will not be fixed and features will not be added unless someone else does so.

If you're interested in fixing up metro-bootstrap, please reply to this [GitHub issue (#65)](https://github.com/TalksLab/metro-bootstrap/issues/65).

Thank you for your support.

**Comment by Bashamega** [comment]
Hello @Jak3b0 
Sorry for the late reply, this project was in active.
Our lib depends on font awesome for logos.
https://github.com/TalksLab/metro-bootstrap/blob/master/package.json
