### ISSUE TITLE
modal-backdrop no need z-index anymore

### ISSUE THREAD

**Issue by iamthom** [TalksLab/metro-bootstrap#59]
in .modal-backdrop, z-index need to be removed. https://github.com/TalksLab/metro-bootstrap/blob/master/dist/css/metro-bootstrap.css#L5377

I used it along with bootstrap 3.2 and the modal works again..

**Comment by fskreuz** [comment]
:+1: This needs to be fixed. Verified on my end.

**Comment by NelsonReis** [comment]
Unfortunately, we no longer have the time to work on this project. This means that bugs will not be fixed and features will not be added unless someone else does so.

If you're interested in fixing up metro-bootstrap, please reply to this [GitHub issue (#65)](https://github.com/TalksLab/metro-bootstrap/issues/65).

Thank you for your support.

**Comment by Bashamega** [comment]
Hello:)
I am sorry for the late reply, i am going to fix it now
