### ISSUE TITLE
Carousel animations doesn't work when I use metro theme

### ISSUE THREAD

**Issue by miladrahimi** [TalksLab/metro-bootstrap#61]
As I mentioned in the title, when I use metro bootstrap, the default Bootstrap carousel doesn't perfectly, it's animations are gone and it slides not smoothly. It's works perfectly when I remove metro CSS dependency. I didn't customized metro theme so it's naturally because of internal metro theme bugs.

**Comment by NelsonReis** [comment]
Unfortunately, we no longer have the time to work on this project. This means that bugs will not be fixed and features will not be added unless someone else does so.

If you're interested in fixing up metro-bootstrap, please reply to this [GitHub issue (#65)](https://github.com/TalksLab/metro-bootstrap/issues/65).

Thank you for your support.
