### ISSUE TITLE
bower info metro-bootstrap return No versions available.

### ISSUE THREAD

**Issue by mbasiuk** [TalksLab/metro-bootstrap#63]
I use "metro-bootstrap": "~3.2.1" in my bower.json file, 

bower info metro-bootstrap
bower metro-bootstrap#\*     not-cached https://github.com/TalksLab/metro-bootstrap.git#*
bower metro-bootstrap#\*        resolve https://github.com/TalksLab/metro-bootstrap.git#*
bower metro-bootstrap#\*       checkout master
bower metro-bootstrap#\*   invalid-meta metro-bootstrap is missing "ignore" entry in bower.json
bower metro-bootstrap#\*       resolved https://github.com/TalksLab/metro-bootstrap.git#b5a7f5e3b3

{
  name: 'metro-bootstrap',
  main: [
    './dist/css/metro-bootstrap.css',
    './dist/fonts/font-awesome/_._',
    './dist/fonts/glyphicons/_._'
  ],
  dependencies: {
    bootstrap: '~3.2.0',
    'font-awesome': '~4.0.0'
  },
  devDependencies: {},
  homepage: 'https://github.com/TalksLab/metro-bootstrap'
}

Please resolve.

**Comment by NelsonReis** [comment]
Unfortunately, we no longer have the time to work on this project. This means that bugs will not be fixed and features will not be added unless someone else does so.

If you're interested in fixing up metro-bootstrap, please reply to this [GitHub issue (#65)](https://github.com/TalksLab/metro-bootstrap/issues/65).

Thank you for your support.

**Comment by Bashamega** [comment]
Hello @mbasiuk 

Sorry for the late reply, this project was inactive. I will try to look at it this week.

**Comment by Bashamega** [comment]
Hello @mbasiuk 
I have published the package to npm, you can try it now using bower or npm or yarn or any package manager

**Comment by mbasiuk** [comment]
Appreciate it!
